version: "3"
services:

  tao-api:
      image: garugaru/tao
      command: ./main serve-api --storage=redis
      environment:
        GIN_MODE: release
        PORT: 80
        STATSD_HOST: ${STATSD_HOST}
        EVENTBRITE_TOKEN: ${EVENTBRITE_TOKEN}
        REDIS_HOST: "tao-redis:6379"
      networks:
        - proxy
        - internal
        - statsd
      deploy:
        labels:
          - traefik.docker.network=proxy
          - traefik.port=80
          - traefik.frontend.rule=Host:dojo.garu.io
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

  tao-scraper:
      image: garugaru/tao
      command: ./main scraper --storage=redis
      environment:
        EVENTBRITE_TOKEN: ${EVENTBRITE_TOKEN}
        STATSD_HOST: ${STATSD_HOST}
        REDIS_HOST: "tao-redis:6379"
        SCRAPER_DELAY: 10800
      networks:
        - internal
        - statsd
      deploy:
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

  tao-redis:
    image: redis:3.2.11-alpine
    networks:
      - internal
    volumes:
        - /swarm/file_store_r2/redis:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure


networks:
  proxy:
    external: true
  internal:
    external: false
  statsd:
    external: true