version: "3"
services:

  tao:
      image: garugaru/tao
      environment:
        GIN_MODE: release
        PORT: 80
        EVENTBRITE_TOKEN: ${EVENTBRITE_TOKEN}
        STATSD_HOST: ${STATSD_HOST}
      networks:
        - proxy
      deploy:
        labels:
          - traefik.docker.network=proxy
          - traefik.port=80
          - traefik.frontend.rule=Host:dojo.garu.pizza
        mode: replicated
        replicas: 1
        restart_policy:
          condition: on-failure

networks:
  proxy:
    external: true
  internal:
    external: false
