version: "3"
services:

  tao:
      command: go test ./... -v
      volumes:
        - ../:/gopath/src/github.com/GaruGaru/Tao
      environment:
        - REDIS_HOST=tao-redis:6379

  tao-faktory:
    image: contribsys/faktory
    ports:
    - 7419:7419
    - 7420:7420
