version: "3"
services:

  tao-api:
      image: garugaru/tao
      command: go run tao.go serve-api
      build:
        context: ../
        dockerfile: docker/Dockerfile.dev
      volumes:
        - ../:/gopath/src/github.com/GaruGaru/Tao
      ports:
        - 8081:8080
      environment:
        - STORAGE=redis
        - REDIS_HOST=tao-redis:6379
        - PORT=8080
        - GIN_MODE=debug
        - EVENTBRITE_TOKEN=TOKEN
      depends_on:
        - tao-redis

  tao-scraper:
      image: garugaru/tao
      command: go run tao.go scraper
      build:
        context: ../
        dockerfile: docker/Dockerfile.dev
      volumes:
        - ../:/gopath/src/github.com/GaruGaru/Tao
      environment:
        - STORAGE=redis
        - REDIS_HOST=tao-redis:6379
        - PORT=8080
        - GIN_MODE=debug
        - EVENTBRITE_TOKEN=TOKEN
      depends_on:
        - tao-redis

  tao-redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379

  tao-faktory:
    image: contribsys/faktory
    ports:
      - 7419:7419
      - 7420:7420
